### ISSUE TITLE
Are these versions the latest one ? I am asking especially about SF mono.

### ISSUE THREAD

**Issue by cata0309** [windyboy1704/San-Francisco-family#1]
*ones, sorry for the typo

**Comment by ebertek** [comment]
Yes, the latest Xcode beta has the same version of SF Mono under /Applications/Xcode-beta.app/Contents/SharedFrameworks/DVTUserInterfaceKit.framework/Versions/A/Resources/Fonts/

**Comment by cata0309** [comment]
Thank you

**Comment by windyboy1704** [comment]
Actually latest beta Xcode version includes newer SF Mono version, `15.0d3e44` (1625 glyphs in total). Unfortunately it's an OpenType font variation, many Windows apps don't support that format so I don't upload it on my repo -- unless I work on it to take the usual weight (from 100 to 900)

**Comment by cata0309** [comment]
Can you share the newer version ? The OpenType version that you mentioned. I am using Linux so no problems for me

**Comment by windyboy1704** [comment]
[SFUIMono.zip](https://github.com/windyboy1704/San-Francisco-family/files/3395567/SFUIMono.zip)
Here it is, Github does not allow TTF so I compressed it into ZIP. Just extract it and it's ready to use.

**Comment by cata0309** [comment]
Thank you very much @windyboy1704

**Comment by cata0309** [comment]
@windyboy1704 is there any way to include the entire family ? I meant the OpenType one, not the ttf

**Comment by windyboy1704** [comment]
I think if you choose the weight according to the font instances, you can include the entire family -- if I understand you correctly

**Comment by cata0309** [comment]
I understand now, it can be tweaked easely to include all weights and
variants

mar., 16 iul. 2019, 09:33 Windy Boy <notifications@github.com> a scris:
